on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: v16.x
          registry-url: "https://registry.npmjs.org"
      - name: Install npm packages
        run: npm install
      - name: typecheck
        run: yarn run typecheck:ci
      - name: lint
        run: yarn run lint:ci
      - name: format
        run: yarn run format:ci
